worker_processes auto;
error_log logs/error.log info;
events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

stream {
    resolver 127.0.0.1;
    lua_add_variable $PORT;
    server {
        listen 80;
        listen 8080;
        listen 443 ssl reuseport backlog=4096;
        listen 8443 ssl reuseport backlog=4096;

        ssl_certificate_key /usr/local/cert/key.pem;
        ssl_certificate /usr/local/cert/cert.pem;
        ssl_preread on;
        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:20m;
        ssl_protocols TLSv1.1 TLSv1 TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
        ssl_prefer_server_ciphers on;

        proxy_buffer_size 256k;
        preread_buffer_size 58;

        preread_by_lua_block {
            local sock, err = ngx.req.socket()

            if not sock then
            ngx.say("failed to get the request socket: ", err)
            return
            end

            local data, err = sock:peek(16)

            -- Functions
            function detect_trojan(sock)
            local buffer_size = 58
            local datal, err = sock:peek(buffer_size)

            if not datal then
            ngx.log(ngx.ERR, "Failed to peek datal: ", err)
            return false
            end

            -- Check if the specified pattern is present in the payload
            if string.byte(datal:sub(57), 1, 2) == 13 then
            ngx.log(ngx.INFO, "Trojan pattern detected!")
            return true
            else
            ngx.log(ngx.INFO, "No Trojan pattern detected.")
            return false
            end
            end

            if string.match(data, "HTTP/1.[01]") then
            -- for Normal http
            ngx.var.PORT = "50000"
            elseif string.match(data, "PRI") and string.match(data, "HTTP/2.0") then
            -- for HTTP2
            ngx.var.PORT = "50001"
            elseif string.match(data, "HTTP") then
            -- for other HTTP versions
            ngx.var.PORT = "50000"
            elseif detect_trojan(sock) then
            -- for Trojan
            ngx.var.PORT = "TROJAN_TCP_PORT"
            else
            -- for V2Ray
            ngx.var.PORT = "VMESS_TCP_PORT"
            end

            ngx.log(ngx.INFO, "Data: ", data)
            ngx.log(ngx.INFO, "TCP stream connection logged with port: ", ngx.var.PORT)
        }
        proxy_pass 127.0.0.1:$PORT;
    }
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log logs/access.log main;
    sendfile on;

    keepalive_timeout 65;

    server {
        listen 50000;
        listen 50001 so_keepalive=on;
        http2 on;
        server_name DOMAIN;

        access_log logs/host.access.log main;

        proxy_http_version 1.1;

        LOCATION_PLACEHOLDER
    }
}