name: Build and Create Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set .netrc
        run: echo ${{ secrets.NETRC }} | base64 --decode > ~/.netrc
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Set go env
        run: go env -w GOPRIVATE=github.com
      - name: Build
        run: |
          go mod tidy
          go build -tags with_grpc,with_clash_api,with_v2ray_api,with_utls,with_reality_server,with_gvisor,with_quic -o latinaserver cmd/latinaserver/main.go
          tar -czvf latinaserver.tar.gz latinaserver
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "latinaserver.tar.gz"
          allowUpdates: true
          tag: "latest"
